/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.*;

/**
 *
 * @author Guhirwa
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form BufferClass
     */
    public App() {
        initComponents();
        setExtendedState(NORMAL);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CreateLink = new javax.swing.JButton();
        UpdateLink = new javax.swing.JButton();
        DeleteLink = new javax.swing.JButton();
        ReadLink = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TAX PAYER REGISTRATION SYSTEM");

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setText("Welcome !!!");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel2.setText("Choose the activity you want to perform:");

        CreateLink.setBackground(new java.awt.Color(255, 255, 204));
        CreateLink.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        CreateLink.setText("Create");
        CreateLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateLinkActionPerformed(evt);
            }
        });

        UpdateLink.setBackground(new java.awt.Color(255, 255, 204));
        UpdateLink.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        UpdateLink.setText("Update");
        UpdateLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateLinkActionPerformed(evt);
            }
        });

        DeleteLink.setBackground(new java.awt.Color(255, 255, 204));
        DeleteLink.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        DeleteLink.setText("Delete");
        DeleteLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteLinkActionPerformed(evt);
            }
        });

        ReadLink.setBackground(new java.awt.Color(255, 255, 204));
        ReadLink.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        ReadLink.setText("Read");
        ReadLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadLinkActionPerformed(evt);
            }
        });

        CancelButton.setBackground(new java.awt.Color(255, 102, 102));
        CancelButton.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Perform CRUD Operation to the taxPayer informations");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(CreateLink)
                .addGap(54, 54, 54)
                .addComponent(UpdateLink)
                .addGap(49, 49, 49)
                .addComponent(DeleteLink)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(ReadLink)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CancelButton)
                        .addGap(208, 208, 208))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateLink)
                    .addComponent(UpdateLink)
                    .addComponent(DeleteLink)
                    .addComponent(ReadLink))
                .addGap(34, 34, 34)
                .addComponent(CancelButton)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateLinkActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new CreateTaxPayer().setVisible(true);
    }//GEN-LAST:event_CreateLinkActionPerformed

    private void UpdateLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateLinkActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new UpdateTaxPayer().setVisible(true);
    }//GEN-LAST:event_UpdateLinkActionPerformed

    private void DeleteLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteLinkActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new DeleteTaxPayer().setVisible(true);
    }//GEN-LAST:event_DeleteLinkActionPerformed

    private void ReadLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadLinkActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ReadData().setVisible(true);
    }//GEN-LAST:event_ReadLinkActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Thank you for using our system!!");
        System.exit(0);
    }//GEN-LAST:event_CancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton CreateLink;
    private javax.swing.JButton DeleteLink;
    private javax.swing.JButton ReadLink;
    private javax.swing.JButton UpdateLink;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
